refactor: 구독 여부 조회 API 헤더에 authorization 추가
SKY-HORSE-MAN-POWER/BE_Members pull request #136
Opened 2024-05-30 18:23 UTC by ddolboghi

- #123 
- 경매글 구독 여부 조회 API 헤더에 authorization 추가하여 API를 호출할때 authorization을 필수 전달하도록 했습니다.

2024-05-31 00:00 UTC, LEEForgiveness approved these changes

2024-05-31 00:01 UTC, hyun7494 approved these changes

2024-05-31 00:30 UTC, LEEForgiveness requested changes

2024-05-31 00:30 UTC, LEEForgiveness commented on src/main/java/com/leeforgiveness/memberservice/subscribe/presentation/AuctionSubscriptionController.java
> +        @RequestHeader String authorization,
게이트웨이에서 authorization을 확인하는데 필요한지 모르겠습니다

2024-06-01 05:17 UTC, ddolboghi commented on src/main/java/com/leeforgiveness/memberservice/subscribe/presentation/AuctionSubscriptionController.java
> +        @RequestHeader String authorization,
경매글 리스트 조회 API에서 이 API를 사용하기 때문에 필요합니다.
리스트 조회 API는 non-authorization이어서 필요없지만, 이 API는 authorization이 필요합니다.

로그인한 유저가 리스트 조회 API를 호출했을때 내부 로직에서 구독 여부 API를 호출하게 되는데, 이때 구독 여부 API는 게이트웨이를 거치기 때문에 헤더에 authorization을 넣어줘야합니다.

다른 API들도 이런 경우가 있을 것 같아 논의가 필요합니다!

2024-06-03 04:58 UTC, ddolboghi commented
경매글 구독 기능을 경매 서비스로 옮기기로 했으므로 PR을 내립니다

2024-06-03 04:58 UTC, closed without merging